name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install deno
        uses: denoland/setup-deno@v1

      - name: Check fmt
        run: deno task check

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install deno
        uses: denoland/setup-deno@v1

      - name: Run unit tests
        run: deno task test
